# Copyright 2020 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
settings:
  name: flyte-triage 
  # On a scale of 0-1, how similar do two issues need to be to be tagged as "similar"
  min_similarity: 0.8
  # Repositories to query, can be overridden by -repos
  repos:
    - https://github.com/flyteorg/flyte
    - https://github.com/flyteorg/flytekit

  member-roles: []
  # Who should automatically be considered a project member?
  # See: https://developer.github.com/v4/enum/commentauthorassociation/
  # Default is "collaborator, owner, member", unless "members" is set
  #
  # member-roles:
  #  - collaborator
  #  - owner
  #  - member
  members: []
  # Who else do we consider to be a project member? Default is empty.
  # members:
  #  - tstromberg

collections:
  - id: daily
    name: Daily Triage
    dedup: false
    description: > 
      Zero out this queue once a day. The priorities are:

       * Keeping an open dialog with our users
       * Initial prioritization (does not have to be perfect)
      Check out the [Triage guidelines](https://github.com/flyteorg/community/blob/main/MAINTAINING.md)
    rules:
      - issue-needs-comment
      - p0-fix-overdue
      - p0-followup-overdue
      # Don't leave code reviews hanging
      - pr-reviewable
      # missing initial feedback
      - issue-needs-kind
      # reprioritize
      - issue-new-with-reactions
      - issue-new-with-many-commenters
      # Don't forget our users
      - issue-has-question
      - issue-updated-has-question

  - id: BiWeekly
    name: Contributors sync
    dedup: true
    description: > 
      Once every 2 weeks, we meet up to address loose ends. The priorities are:

       * Keeping an open dialog with our users
       * Finding misprioritized issues
      Check out the [Triage guidelines](https://github.com/flyteorg/community/blob/main/MAINTAINING.md)
    rules:
      - discuss
      # Issues needing reprioritization
      - many-reactions
      - many-commenters
      # Issues needing reprioritization
      - issue-zombies
      # Issues needing closure
      - issue-stale-needs-info
      - issue-stale-support
      # PR's needing closure
      - pr-approved-stale
      - pr-unapproved-stale
      # People with questions
      - issue-has-question
      - issue-updated-has-question
   

  - id: quarterly
    name: Quarterly Scrub
    dedup: true
    description: >
      Once every quarter, we look for stale issues and de-duplicate

      The priorities for this page are:

       * De-duplication
       * Keeping the bug queue relevant
       * Making tough decisions about long-standing requests
    rules:
      - birthday
      - lifecycle-rotten
      - question-old
      - bugs-old
      - enhancement-old
      - other-old

  # - id: milestone
  #   name: In Milestone
  #   description: >
  #     A Kanban visualization of milestones, showing the flow of issues through each stage.

  #       * Unassigned issues represent available work
  #       * >3 issues assigned to the same person within a stage signifies a bottleneck 🌊
  #   display: kanban
  #   overflow: 3
  #   dedup: true
  #   rules:
  #     - milestone-not-started
  #     - milestone-assignee-updated
  #     - milestone-pr-needs-review
  #     - milestone-pr-needs-work
  #     - milestone-pr-needs-merge
  #     - milestone-recently-closed

  # - id: recv
  #   name: "Receive queue"
  #   description: >
  #     Issues that may be waiting for our response

  #     NOTE: for this to work properly, GitHub token must have read access to read organization members
  #   rules:
  #     - question-recv
  #     - bugs-recv
  #     - enhancement-recv
  #     - other-recv

  - id: p0
    name: P0
    description: All hands on deck!
    rules:
      - p0-prs
      - p0-features
      - p0-bugs
      - p0-other

  - id: p1
    name: P1
    description: To be resolved within 6 weeks
    rules:
      - p1-prs
      - p1-features
      - p1-bugs
      - p1-other

  - id: similar
    name: Similar
    description: Items which appear similar to one other. Review for duplicates or vague titles.
    rules:
      - similar-prs
      - similar-issues

  - id: __open__
    name: All open PR's and Issues that should be considered for repository stats (hidden)
    used_for_statistics: true
    hidden: true
    rules:
      - open-prs
      - open-issues

  - id: __velocity__
    name: issues to include in velocity metrics
    used_for_statistics: true
    hidden: true
    rules:
      - closed-milestone-issues

rules:
  ### Daily Triage ####
  issue-needs-comment:
    name: "Unresponded, older than 7 days"
    resolution: "Respond to the issue"
    type: issue
    filters:
      #- tag: "!commented" RunLLM typically adds comments
      #- tag: "recv"
      - created: +1w
      - label: "untriaged"
      - label: "!stale"

  # Don't leave code reviews hanging
  pr-reviewable:
    name: "Pull Requests: Review Ready"
    resolution: "Review requests or mark them as do-not-merge/work-in-progress"
    type: pull_request
    filters:
      - label: "!do-not-merge"
      - label: "!needs-rebase"
      - label: "!.*wip"
      - label: "!cncf-cla: no"
      - tag: "!changes-requested"
      - tag: "!send"
      - tag: "!commented"
      - tag: "!draft"
      - tag: "!approved"

      # Temporarily workaround inability to track PR eligibility
      - updated: +1d

  # Issues missing initial feedback
  issue-needs-kind:
    name: "Unlabeled Issues"
    resolution: "Add a label"
    type: issue
    filters:
      - label: "!.*(kind|bug|documentation|enhancement|question|todo|idea|epic).*"
      - label: "!stale"
  # Issues that may need reprioritized
  issue-new-with-reactions:
    name: "New, has multiple reactions, but not p0"
    resolution: "Check if issue should be prioritized as p0"
    type: issue
    filters:
      - reactions: ">2"
      - created: -10d
      - tag: "!send"
      - label: "!priority/p0"

  issue-new-with-many-commenters:
    name: "New, has multiple commenters, but not p0"
    resolution: "Check if issue should be prioritized as p0"
    type: issue
    filters:
      - commenters: ">3"
      - created: -10d
      - tag: "!send"
      - label: "!priority/p0"

  # People with questions
  issue-updated-has-question:
    name: "Question not responded to for over two weeks"
    resolution: "Remove question label, or add a comment"
    type: issue
    filters:
      - tag: recv
      - label: "question"
      - tag: "!member-last"
      - tag: "!contributor-last"
      - label: "!triage/discuss"
      - responded: +15d

  issue-has-question:
    name: "Reporter asked a follow-up question over a week ago"
    resolution: "Add an answer"
    type: issue
    filters:
      - tag: recv-q
      - tag: "!member-last"
      - tag: "!contributor-last"
      - responded: +7d

  ####### Weekly Triage #########
  discuss:
    name: "Items for discussion"
    resolution: "Discuss and remove label"
    filters:
      - label: "triage/discuss"
      - state: "all"
      - label: "!stale"
  # SLO nearing
  p0-followup-overdue:
    name: "p0 issue, no comments in 3 days"
    resolution: "Downgrade to p1"
    type: issue
    filters:
      - label: "priority/p0"
      - tag: recv
      - responded: +3d

  p0-fix-overdue:
    name: "p0 bug, older than 7 days"
    resolution: "Downgrade to p1"
    type: issue
    filters:
      - label: "priority/p0"
      - created: +7d

  # issues needing reprioritization
  many-reactions:
    name: "many reactions, low priority, no recent comment"
    resolution: "Bump the priority, add a comment"
    filters:
      - reactions: ">3"
      - reactions-per-month: ">1"
      - label: "!priority/p0"
      - label: "!priority/p1"
      - responded: +60d

  many-commenters:
    name: "many commenters, low priority, no recent comment"
    resolution: "Consider increasing priority"
    type: issue
    filters:
      - commenters: ">3"
      - commenters-per-month: ">1.9"
      - created: "+30d"
      - label: "!priority/p0"
      - label: "!priority/p1"
      - tag: "!member-last"
      - responded: "+60d"

  issue-zombies:
    name: "Screaming into the void"
    resolution: "Reopen, or ask folks to open a new issue"
    type: issue
    filters:
      - state: closed
      - comments-while-closed: ">1"
      - updated: "-14d"
      - tag: "!member-last"

  # Issues needing closure
  birthday:
    name: "Forgotten Birthdays - over a year old, no response in 6 months"
    resolution: "Close or comment on what it would take to address this issue"
    filters:
      - created: +365d
      - responded: +180d
  
  issue-stale-needs-info:
    name: "Needs reproduction for over 3 weeks"
    resolution: "Close or remove needs-reproduction label"
    type: issue
    filters:
      - label: needs-reproduction
      - responded: +1w
      - updated: +21d

  issue-stale-support:
    name: "Question over 30 days old"
    resolution: "Close, or add to documentation"
    type: issue
    filters:
      - label: question
      - updated: +30d
      - responded: +7d

  lifecycle-rotten:
    name: "P2+ over 180 days old without a recent response"
    resolution: "Close or add discuss label"
    filters:
      - created: +180d
      - responded: +90d
      - label: "!priority/p3"
      #- label: "!priority/awaiting-more-evidence"
      - label: "!triage/discuss"

  # PR's needing closure
  pr-approved-stale:
    name: "Pull requests: Approved and getting old"
    resolution: "Close, comment, or add discuss label"
    type: pull_request
    filters:
      - label: "!do-not-merge.*"
      - label: "!needs-rebase"
      - label: "lgtm"
      - updated: +5d
      - responded: +2d
      - label: "!triage/discuss"
      - tag: "approved"

  pr-unapproved-stale:
    name: "Unapproved stale PRs"
    resolution: "Close, comment, or add discuss label"
    type: pull_request
    filters:
      - created: +20d
      - updated: +5d
      - responded: +2d
      - label: "!triage/discuss"
      - tag: "!draft"

  ## Bug Scrub ##
  question-old:
    name: "Questions that have been open for >6 weeks"
    resolution: "Comment or close the issue"
    type: issue
    filters:
      - responded: +7d
      - created: +42d
      - label: "question"

  enhancement-old:
    name: "Feature requests that have not been commented on within 90 days"
    resolution: Comment, close, or add triage/discuss label"
    type: issue
    filters:
      - responded: +90d
      - created: +90d
      - label: "enhancement"
      - label: "!triage/discuss"

  bugs-old:
    name: "Bugs that have not been commented on within 90 days"
    resolution: "Comment, close, or add discuss label"
    type: issue
    filters:
      - label: "bug"
      - responded: +90d
      - created: +90d
      #- label: ".*(!priority/awaiting-evidence).*"
      - label: "!stale" #not processed yet by the stale bot 

  other-old:
    name: "Other items that have not been commented on within 90 days"
    resolution: "Comment or close the issue"
    type: issue
    filters:
      - responded: +90d
      - created: +90d
      - label: "!question"
      - label: "!.*(feature|enhancement).*"
      - label: "!.*bug"

  # Receive queue
  question-recv:
    name: "Questions awaiting follow-up"
    resolution: "Comment or close the issue"
    type: issue
    filters:
      - tag: recv
      - label: "question"

  bugs-recv:
    name: "Bugs awaiting follow-up"
    resolution: "Comment or close the issue"
    type: issue
    filters:
      - tag: recv
      - label: "bug"

  enhancement-recv:
    name: "Features awaiting follow-up"
    resolution: "Comment or close the issue"
    type: issue
    filters:
      - tag: recv
      - label: ".*(feature|enhancement|idea).*"

  other-recv:
    name: "Items that deserve a follow-up comment"
    resolution: "Comment or close the issue"
    type: issue
    filters:
      - tag: recv
      - responded: +30d
      - label: "!enhancement"
      - label: "!.*bug"
      - label: ".*question"

  # P0
  p0-features:
    name: "p0 Bugs"
    type: issue
    resolution: Close or deprioritize
    filters:
      - label: "priority/p0"
      - label: "bug"

  p0-bugs:
    name: "p0 Features"
    type: issue
    resolution: Close or deprioritize
    filters:
      - label: "priority/p0"
      - label: "enhancement"

  p0-other:
    name: "p0 Other"
    type: issue
    resolution: Close or deprioritize
    filters:
      - label: "priority/p0"
      - label: "!enhancement"
      - label: "!bug"

  p0-prs:
    name: "p0 Pull Requests"
    type: pull_request
    resolution: Merge em
    filters:
      - label: "priority/p0"

  # P1
  p1-bugs:
    name: "p1 Bugs"
    type: issue
    resolution: Close or deprioritize
    filters:
      - label: "priority/p1"
      - label: "bug"

  p1-features:
    name: "p1 Features"
    type: issue
    resolution: Close or deprioritize
    filters:
      - label: "priority/p1"
      - label: "enhancement"

  p1-other:
    name: "p1 Other"
    type: issue
    resolution: Close or deprioritize
    filters:
      - label: "priority/p1"
      - label: "!enhancement"
      - label: "!bug"

  p1-prs:
    name: "p1 Pull Requests"
    type: pull_request
    resolution: Merge em
    filters:
      - label: "priority/p1"

  ## Similar
  similar-prs:
    name: "Similar Pull Requests"
    type: pull_request
    resolution: Close as duplicate or give a better title
    filters:
      - tag: similar

  similar-issues:
    name: "Similar Issues"
    type: issue
    resolution: Close as duplicate or give a better title
    filters:
      - tag: similar

  ### Milestone Kanban ###
  milestone-not-started:
    name: "Not started"
    type: issue
    filters:
      - tag: open-milestone
      - tag: "!assignee-updated"
      - tag: "!(assignee-open-pr|assignee-closed-pr)"
  milestone-assignee-updated:
    name: "In Progress"
    type: issue
    filters:
      - tag: open-milestone
      - tag: "assignee-updated"
      - tag: "!(pr-changes-requested|pr-reviewer-comment|pr-unreviewed|pr-new-commits|pr-approved|pr-changes-requested)"
  milestone-pr-needs-work:
    name: "PR needs work"
    type: issue
    filters:
      - tag: open-milestone
      - tag: "(pr-changes-requested|pr-reviewer-comment)"
  milestone-pr-needs-review:
    name: "PR needs Review"
    type: issue
    filters:
      - tag: open-milestone
      - tag: "(pr-unreviewed|pr-new-commits)"
  milestone-pr-needs-merge:
    name: "PR needs Merge"
    type: issue
    filters:
      - tag: open-milestone
      - tag: "(pr-approved|pr-approved-but-pushed)"
  milestone-recently-closed:
    name: "Finish Line"
    type: issue
    filters:
      - tag: open-milestone
      - state: closed
      - updated: -21d

  # for statistics generation
  open-issues:
    name: "Open Issues"
    type: issue

  open-prs:
    name: "Open PRs"
    type: pull_request

  closed-milestone-issues:
    name: "Recently closed milestone issues"
    type: issue
    filters:
      - state: closed
      - closed: -90d
      - milestone: ".*"
      - label: "!triage/duplicate"
